# Generated by Django 5.0.3 on 2024-04-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='category',
            new_name='product_category',
        ),
    ]
