# Generated by Django 5.0.3 on 2024-05-06 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_category_productmodel_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cart_date', models.DateTimeField(auto_now_add=True)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmodel')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
