# Generated by Django 5.0.3 on 2024-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='cart_total_price',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cart_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
