# Generated by Django 5.0.3 on 2024-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
