# Generated by Django 5.0.3 on 2024-05-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_ordermodel_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(default='Booked', max_length=100),
        ),
    ]
