# Generated by Django 5.0.3 on 2024-05-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_ordermodel_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_status',
        ),
    ]
