# Generated by Django 5.0.3 on 2024-06-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_ordermodel_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_quantity',
            field=models.IntegerField(),
        ),
    ]
